package:
  format-version: "1.0.0"
  name: "net_apps_sam_a7g5"
  version: "3.0.0"
  type: "application"
  status: "production"
  
  dependencies:
    - name: "core"
      type: "package"
      version: "v3.12.0-E1"
    - name: "csp"
      type: "package"
      version: "v3.15.0"
    - name: "bsp"
      type: "package"
      version: "v3.15.1"
    - name: "dev_packs"
      type: "package"
      version: "v3.15.1"
    - name: "crypto"
      type: "package"
      version: "v3.7.6"
    - name: "net"
      type: "package"
      version: "3.9.1"
    - name: "wolfssl"
      type: "package"
      version: "v4.7.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.4.6"
