format_version: v1.0
configName: sam_a7g5_ek_GMAC0_freertos
folderName: tcpip_tcp_server_GMAC0_freertos
frameworkPath: C:\00_Repo\H3
processor: SAMA7G54
projectName: tcpip_tcp_server_GMAC0_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMA7G5_DFP\1.0.56\atdf\SAMA7G54.atdf
